### ISSUE TITLE
float/double digits wrong when using higher precision

### ISSUE THREAD

**Issue by adammj** [DarkWishMaster/TinyStdio#3]
This is using a TI TMS320F2837xS. When using the default 6 digits of precision, the printout will print slightly wrong digits. (and when using any specific digits of precision, the print will not round the last digit).

For example: (the colons are there just to help emphasize the start and end)
TINY_PRINTF_FP_PRECISION = 6
float f_value = 2.3467216;
printf(":%f:\r\n", f_value); gives ":2.5880:"
printf(":%.1f:\r\n", f_value); gives ":2.3:"
printf(":%.2f:\r\n", f_value); gives ":2.34:"
printf(":%.3f:\r\n", f_value); gives ":2.346:"
printf(":%.4f:\r\n", f_value); gives ":2.3467:"
printf(":%.5f:\r\n", f_value); gives ":2./0))-:"
printf(":%.6f:\r\n", f_value); gives ":2.5880:"
printf(":%.7f:\r\n", f_value); gives ":2.'-*,:"

double d_value = 2.3467216;
printf(":%F:\r\n", d_value); gives "2.5880"
printf(":%.1F:\r\n", d_value); gives "2.3"
printf(":%.2F:\r\n", d_value); gives "2.34"
printf(":%.3F:\r\n", d_value); gives "2.346"
printf(":%.4F:\r\n", d_value); gives "2.3467"
printf(":%.5F:\r\n", d_value); gives "2./0))-"
printf(":%.6F:\r\n", d_value); gives "2.5880"
printf(":%.7F:\r\n", d_value); gives "2.'-*,"

**Comment by vladcebo** [comment]
Just ran your example on TM4C123GH6PM (GNU ARM toolchain/ CodeSourcery toolchain) and also tried with cygwin and mingw32 on my machine, all works.
Looks like by increasing the accuracy some gibberish output appears like '-*', maybe something writes on that stack?

![image](https://cloud.githubusercontent.com/assets/6986879/23591321/1d6ba824-01f7-11e7-9640-30a5343a2175.png)

```
void TerminalPrintf(char* format, ...)
{
	char data[100];

	va_list valist;
	va_start(valist, format);

	uint32_t n = (uint32_t)tfp_vsnprintf(data, 100, format, valist);
	SerialTransmit((uint8_t*)data, n);

}
```

**Comment by adammj** [comment]
I'll have to play with it further this week. I could increase the stack and see what happens.

**Comment by adammj** [comment]
I added a breakpoint to check for writing to the end of the stack - no issues. I wonder if this has anything to do with the char size on the TMS320F2837xS: the minimum size is 16bits (so char, short, etc are all full 16bits wide - although they only use 8bit to describe the value)

**Comment by adammj** [comment]
I figured it out. Your code makes the assumption that "int" is always 32 bits wide (regardless of architecture). So when the %f code is running it overflows quite soon with a 16 bit wide integer. I switched all of the "int"s to "int32_t" and all "unsigned int" to "uint32_t". I think that you should probably update your code to use the C99 specifications which require specifying the desired width for every type.


btw. Thank you. This is a pretty small printf replacement (and the floating print out has been the only issue I've had with it).

**Comment by vladcebo** [comment]
Hey, thank you for your feedback, I'll update the implementation to use stdint.
